### ISSUE TITLE
Add "Download" and "Upload" in Remote Explorer context menu

### ISSUE THREAD

**Issue by NyaPPuu** [Natizyskunk/vscode-sftp#161]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [x] No.

**Is your feature request related to a problem? Please describe.**
You can download or upload with command.
But it will be very convenient to use if it is in the context menu of the Remote Explorer.

**Describe the solution you'd like**
If you right-click on the remote explorer folder, "Download Folder" and "Upload Folder" are displayed.
For files, "Download" and "Upload" are displayed.
like local explorer.

**Describe alternatives you've considered**
I think it would be a good idea to add upload and download buttons next to the refresh button in Remote Explorer.

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!

**Comment by Natizyskunk** [comment]
@NyaPPuu,
The `Download File` & `Downalod Folder` features in the remote explorer has been added in the latest 1.15.20 release.
For the `Upload File` & `Upload folder` this has no sense to add those in the remote explorer because you wouldn't upload on the remote a file that is already on the remote (because this is what you're browsing). 
If you wnat to upload a file or a folder just use the default options available in your vscode local explorer.

**Comment by NyaPPuu** [comment]
> @NyaPPuu, The `Download File` & `Downalod Folder` features in the remote explorer has been added in the latest 1.15.20 release. For the `Upload File` & `Upload folder` this has no sense to add those in the remote explorer because you wouldn't upload on the remote a file that is already on the remote (because this is what you're browsing). If you wnat to upload a file or a folder just use the default options available in your vscode local explorer.

@Natizyskunk 
If you set the sidebar to open only one tab,
You must find and edit files in Remote Explorer, then reopen Local Explorer, locate and upload files.

Local Explorer also has both download and upload. This is not strange.

**Comment by Natizyskunk** [comment]
I see, That not wrong. I'll take a look ok.
