### ISSUE TITLE
Upload changed files not working 

### ISSUE THREAD

**Issue by jano23** [Natizyskunk/vscode-sftp#178]
**Do you read the FAQ?**
- [x] Yes.

Tried the suggested fix of Issue #108: uninstalling all versions, deleting all occurrences of the extension, restarting vscode and reinstalling."
Output on Terminal shows UPLOAD: results correctly on the 3 files I am testing but the server still has the old versions.
SFTP v1.15.14
VSCODE v1.70.0

**To Reproduce**
1. Go to F1
2. Run command SFTP: Upload Changed Files - Ctrl + Alt +U
3. No error

**Expected behavior**
Upload the changed files

**Desktop (please complete the following information):**
 - OS: Win 11
 - VSCode Version 1.70.0
 - Extension Version 1.15.14

Terminal output:
[08-11 17:21:17] 
[08-11 17:21:17] ------ Upload Changed Files Result ------
[08-11 17:21:17] UPLOAD:
[08-11 17:21:17] /****.asp
/**/****.asp
/**/****.asp
/****.asp
/****.asp
(removed file names)

**Comment by jano23** [comment]
UPDATE:

Looks like it was port configuration issue.  I am using ftp protocol and if I try port 21 or 22 it doesn't upload changed files. If I remove the port line in sftp.json then changed files are updloaded but they show the timestamp of the time of upload, not the timestamp of when the file was changed.

**Comment by Natizyskunk** [comment]
@jano23,
This is not related to the vscode-sftp extension. This mean that you've a problem with your ftp configuration on your server (by default ftp is port 21 et ssh/ftps is port 22). Don't try port 22 on ftp and vice-versa (port 21 on ssh/ftps).

For the timestamp it's normal because when you upload a file it's updated (**changed**) on your server. This mean the timestamp is acutally correctly set to the time when the file was changed (**updated**).
