### ISSUE TITLE
Clarify the differences with the fork by viperet

### ISSUE THREAD

**Issue by iaeiou** [Natizyskunk/vscode-sftp#21]
Hello there,

thanks for keeping `vscode-sftp` alive.

There are two different forks actively developed, could you please explain the differences/similarities with [this other fork](https://github.com/viperet/vscode-sftp-revived)?

Thank you

NB: the same question was asked there: https://github.com/viperet/vscode-sftp-revived/issues/6

**Comment by Natizyskunk** [comment]
I'm trying to actively maintain this extension and fixing every problem that has been introduce since the update of the ssh2 package to v1.1.0. As you can see, it seems that my version is the most up to date as it seems that it's been at least two months since viperet haven't made any update/commits and he's also not responding to open issues but feel free to use the one you prefer 🙂
