### ISSUE TITLE
Rename file or folder of remote

### ISSUE THREAD

**Issue by satiromarra** [Natizyskunk/vscode-sftp#278]
Would it be possible to change the name of the remote file or directory from the sftp explorer?

**Comment by eigenstil** [comment]
@Natizyskunk is there any answer for this question?

**Comment by eigenstil** [comment]
Wow – great @satiromarra! 👍

**Comment by Natizyskunk** [comment]
@satiromarra,

Can you please open a pull request like it is described in [this guide](https://github.com/Natizyskunk/vscode-sftp/blob/master/CONTRIBUTING.md) ? Please follow [this template](https://github.com/Natizyskunk/vscode-sftp/issues/new?assignees=&labels=&template=pull_request.md&title=).
I would be more than happy to merge your work as this is the new official repo.

**Comment by Natizyskunk** [comment]
@satiromarra Still waiting on your pull request. You didn't answer me and the others. instead you're keeping yet another fork and publishing on the visual studio Marketplace as the official new fork but this is false. It would be nice and so easier if we could work together and keep this repo the official one as I've worked hard on it since almost two years.
