### ISSUE TITLE
 Ignore setting does not prevent deletion of specific folder on server

### ISSUE THREAD

**Issue by LigarbaCom** [Natizyskunk/vscode-sftp#489]
I'm experiencing an issue with the SFTP extension (v1.16.3) for Visual Studio Code where the ignore settings do not prevent the deletion of a specific folder on the server.

1. Configure the sftp.json file with the following settings:

`{
  "name": "mysite",
  "host": "mysite.com",
  "protocol": "ftp",
  "secure": true,
  "secureOptions": {
      "rejectUnauthorized": false
  },
  "port": 21,
  "watcher": {
      "files": "**/*",
      "autoUpload": true,
      "autoDelete": true
  },
  "username": "username",
  "password": "password",
  "remotePath": "/",
  "uploadOnSave": true,
  "ignore": [".vscode", ".git","db/", ".DS_Store","node_modules/", "client/", ".gitignore", ".env",".env.sample","img/"]
}
`
2. In the local project, delete some files and folders, including those in the public directory but NOT in the public/img folder.

3. Upon saving, the public/img folder and its contents are also deleted on the server, despite being included in the ignore settings.

Expected Behavior:
The public/img folder and its contents should remain intact on the server, even if they are deleted locally.

Actual Behavior:
The public/img folder and its contents are deleted on the server when deleted locally, despite being listed in the ignore settings.

Environment:

    VS Code version: 1.89.1
    SFTP extension version: 1.16.3
    OS: [MacOS]

Additional Context:
It is crucial for my workflow to keep the public/img folder intact on the server, while other files and folders can be deleted. Any guidance on how to properly configure the ignore settings to achieve this would be greatly appreciated.

**Comment by tomsour1s** [comment]
Hey, 

I tried to recreate your Issue. I created a local folder-structure like this:

```bash
├───.vscode
│       sftp.json
│       
└───public
    ├───img
    └───services
            foo.py
```

On the remote server I added a image to: `public/img/logo.png`
I synched and the img is still on the remote server, even if the local img folder is empty. If I understood your correctly that is the part that is not working for you.

In your Issue you mentioned:
> Upon saving, the public/img folder and its contents are also deleted on the server

In your posted config, inside the ignore array, you just configured **img/** and not **public/img/**. But maybe that is just a typo. The problem should be fixed with: 
**/public/img/*** or, if it was just a typo with 
**/img/***

Tested it with success:

```
"ignore": [
     ".vscode",
      ".git",
      ".DS_Store",
      "/public/img/*"
]
```

I hope that helps :v:

**Comment by LigarbaCom** [comment]
I changed that as **/img , for all img folders, ok worked
