### ISSUE TITLE
Connection to secure cPanel server: ECONNREFUSED

### ISSUE THREAD

**Issue by GreenSpanner** [Natizyskunk/vscode-sftp#62]
**Do you read the FAQ?**
- [ y] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
Failed to start ftp with error ECONNREFUSED

**To Reproduce**
1. Go to 'vscode'
2. Run command 'sftp:Config'
3. See error
ECONNREFUSED
**Expected behavior**
See a list of files and folders from the server in the left window pane.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Win, Linux]
 - VSCode Version [e.g. 1.51.0]
 - Extension Version [e.g. 1.7.0]
Windows 10, 
Vsc 1.60.1
**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.
[09-20 14:11:26] [info] config at c:\Users\Tc\Documents {"remotePath":"/","uploadOnSave":false,"useTempFile":false,"openSsh":false,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"My Test Server","host":"ftp.tc4.co.uk","username":"******","password":"******"}
[09-20 14:11:26] [debug] Custom crypto binding not available
[09-20 14:11:26] [debug] Client: Trying ftp.tc4.co.uk on port 22 ...
[09-20 14:11:26] [debug] Local ident: 'SSH-2.0-ssh2js1.4.0'
[09-20 14:11:28] [debug] Socket error: connect ECONNREFUSED 193.189.75.42:22
[09-20 14:11:28] [debug] Socket closed
![vscode sftp screenshot #1](https://user-images.githubusercontent.com/91069527/134009252-a5872445-ecdc-412b-9f51-bd41006d713e.jpg)

**Comment by Natizyskunk** [comment]
@GreenSpanner,

Only things I can think of : 
- Bad configuration file (verify username & password).
- OpenSsh connection bug.
- non-supported transport layer algorithms.

So firstly just check your sftp.json config file and verify that everything is correct.

Then you can you try to switch "useTempFile" and "openSsh" options to `true` to enable atomic file upload for supported server.
If this is not working please revert it back to default (`'false'`).

Now if your problem is still not fixed, you can try this : 

FAQ : https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md#error-connection-closed

The problem would be that the SFTP extension keeps closing the connection for those who use more legacy/old systems. You'll have to Explicitly override the default transport layer algorithms used for the connection to remove the new "diffie-hellman-group-exchange-sha256" algorithm that cause the problem from the kex section. Just add this in your sftp.json config file, which should make it work.
```json
{
	...
	"host": "exemple.com",
	...
	"algorithms": {
		"kex": [
			"ecdh-sha2-nistp256", 
			"ecdh-sha2-nistp384", 
			"ecdh-sha2-nistp521", 
			"diffie-hellman-group14-sha1"
		],
		"cipher": [
			"aes128-ctr", 
			"aes192-ctr", 
			"aes256-ctr", 
			"aes128-gcm", 
			"aes128-gcm@openssh.com", 
			"aes256-gcm", 
			"aes256-gcm@openssh.com"
		],
		"serverHostKey": [
			"ssh-rsa", 
			"ecdsa-sha2-nistp256", 
			"ecdsa-sha2-nistp384", 
			"ecdsa-sha2-nistp521"
		],
		"hmac": [
			"hmac-sha2-256", 
			"hmac-sha2-512", 
			"hmac-sha1"
		]
	}
}
```


**References:** 
_Originally posted by @montorodiaz in https://github.com/liximomo/vscode-sftp/issues/883#issuecomment-783402096_
https://github.com/liximomo/vscode-sftp/wiki/SFTP-only-Config#sshcustomparams

**Comment by GreenSpanner** [comment]
1)
Testing username / password in Filezilla
<img width="1152" alt="filezilla-test-creds" src="https://user-images.githubusercontent.com/91069527/135096682-54295d07-0e50-4cc7-94ea-06225a2f0883.png">

2)
Trying     "useTempFile":true,
	"openSsh": true
Is the "Custom crypto binding not available" a possible clue here?
<img width="1269" alt="vscode-sftp-useTempFile-openSsh" src="https://user-images.githubusercontent.com/91069527/135097046-b0872100-a40a-4497-889a-accb8a325689.png">

3)
Trying "algorithms": {... }
<img width="1269" alt="vscode-sftp-algs" src="https://user-images.githubusercontent.com/91069527/135097433-9cda5274-10a1-4fa3-bfd1-661c7787c283.png">

**Comment by GreenSpanner** [comment]
I managed to resolve this myself after almost 5 months of thinking it was impossible.  Here are the settings that worked for me...

{
    "name": "myname",
    "host": "ftp.mywebsite.co.uk",
    "protocol": "ftp",
    "secure": true,
    "username": "myusername",
    "password": "mypassword",
    "remotePath": "/public_html/",
    "secureOptions": {
        "rejectUnauthorized": false
    },
    "uploadOnSave": false,
    "useTempFile": false,
    "openSsh": true
}
I hope it helps someone else.
